### ISSUE TITLE
Buying error and item limit

### ISSUE THREAD

**Issue by DerHobbs** [VORPCORE/vorp_stores-lua#18]
On the one hand, if you click away windows, you still buy the things, on the other hand, the item limit doesn't work for me at all, I've done everything as instructed, but I can still buy and sell as many as I want.

https://streamable.com/5zzc5r

**Comment by outsider31000** [comment]
@Dietrich-io

**Comment by Dietrich-io** [comment]
Cant help you with the first Bug. It's something i noticed before my update aswell. Seems to be an vorp_input issue, but i can't tell because i didn't figuered it out either. 
Also tested the limitations on my Server and they seem to work fine. May you can provide more information on that? :)
Is the limitation not even displayed? Or when you can buy or sell everything is the display changing etc.? 
Otherwise contact me directly and i am trying to help.

**Comment by Dietrich-io** [comment]
Before Selling Example:
![image](https://user-images.githubusercontent.com/102512250/183578092-a86c6829-7fc8-4b59-b42a-8bd63c055be3.png)

After Selling Example:
![image](https://user-images.githubusercontent.com/102512250/183578212-852c8503-fe7b-479e-aedd-c5b2cc154a71.png)

**Comment by DerHobbs** [comment]
I've tried all possible variants, doesn't work.

But it's not bad, at first I thought I could only BUY what was SOLD, but it's ONLY a limit, that's no use, so it doesn't matter.

**Comment by outsider31000** [comment]
you have 10 initial items  if you buy alll the store wont have any  if you then sell 5 to the store  the store will have 5 to sell again

**Comment by DerHobbs** [comment]
Yes, but it is not saved anywhere ;) the status of the items would have to be saved in the DB, then it makes sense.

**Comment by outsider31000** [comment]
its on a table  @DerHobbs  no need for DB so every restart they get re stocked

**Comment by outsider31000** [comment]
![image](https://user-images.githubusercontent.com/87246847/183653484-9abc8b03-e795-4d83-b672-0ab4045b0b7a.png)

**Comment by outsider31000** [comment]
they are stored in here
